### ISSUE TITLE
Code for STM32?

### ISSUE THREAD

**Issue by sonata82** [Seeed-Studio/Grove_Triple_Color_E-lnk_2.13#3]
In the README.md it says:

> If you need to change the startup code, check out the library's code for STM32.

But I can't find the code in this repository. Can you tell me where I can find it?

**Comment by Kongduino** [comment]
Any update on this? Thanks.

**Comment by fedelodo** [comment]
I'm also interested in this

**Comment by pmanstein** [comment]
Or is there any more documentation but the example code?
